# Site settings
title: how your mind works
email: akenney@alum.mit.edu
description: > # this means to ignore newlines until "baseurl:"
  Reference materials for class for ESP Cascade 2015.
baseurl: "/mind-cascade" # the subpath of your site, e.g. /blog/
url: "http://akenney.github.io" # the base hostname & protocol for your site
github_username:  akenney

# Build settings
markdown: kramdown
